# 设置默认 shell
set shell := ["bash", "-cu"]

# 可选：默认任务
default:
    just deploy

# 更新 flake & rebuild 系统
deploy:
    # 可选：释放 nix store 空间
    # nix store gc

    # echo "🔄 Updating flake..."
    # nix flake update

    echo "🔨 Building system..."
    nix build .#darwinConfigurations.zeds.system \
        --extra-experimental-features 'nix-command flakes'

    echo "🚀 Switching system configuration..."
    sudo ./result/sw/bin/darwin-rebuild switch --flake .#zeds
