{ pkgs, ... }: {

  ##########################################################################
  # 
  #  Install all apps and packages here.
  #
  #  NOTE: Your can find all available options in:
  #    https://daiderd.com/nix-darwin/manual/index.html
  # 
  # TODO Fell free to modify this file to fit your needs.
  #
  ##########################################################################

  # Install packages from nix's official package repository.
  #
  # The packages installed here are available to all users, and are reproducible across machines, and are rollbackable.
  # But on macOS, it's less stable than homebrew.
  #
  # Related Discussion: https://discourse.nixos.org/t/darwin-again/29331
  environment.systemPackages = with pkgs; [
    git
    yadm
    mosh
    nixpkgs-fmt
    procs
    bat
  ];
  environment.variables = {
    HOMEBREW_API_DOMAIN = "https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api";
    HOMEBREW_BOTTLE_DOMAIN = "https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles";
    HOMEBREW_BREW_GIT_REMOTE = "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git";
    HOMEBREW_CORE_GIT_REMOTE = "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git";
    HOMEBREW_PIP_INDEX_URL = "https://pypi.tuna.tsinghua.edu.cn/simple";
  };
  # TODO To make this work, homebrew need to be installed manually, see https://brew.sh
  # 
  # The apps installed by homebrew are not managed by nix, and not reproducible!
  # But on macOS, homebrew has a much larger selection of apps than nixpkgs, especially for GUI apps!
  homebrew = {
    enable = true;

    onActivation = {
      autoUpdate = false;
      cleanup = "zap";
    };

    taps = [
      "homebrew/cask-fonts"
      "homebrew/services"
      "homebrew/cask-versions"
      "beeftornado/rmtree"
      "homebrew/bundle"
      "homebrew/command-not-found"
      "sunnyyoung/repo"
    ];

    # `brew install`
    brews = [
      "aom"
      "aria2"
      "aribb24"
      "axel"
      "bazel"
      "bdw-gc"
      "berkeley-db"
      "boost"
      "brew-cask-completion"
      "brotli"
      "c-ares"
      "ca-certificates"
      "cairo"
      "cjson"
      "clang-format"
      "cmake"
      "cscope"
      "dav1d"
      "enca"
      "ffmpeg"
      "flac"
      "fontconfig"
      "freetype"
      "frei0r"
      "fribidi"
      "gd"
      "gdbm"
      "gettext"
      "gh"
      "ghostscript"
      "giflib"
      "git-lfs"
      "glib"
      "gmp"
      "gnutls"
      "gobject-introspection"
      "graphite2"
      "gts"
      "harfbuzz"
      "highway"
      "htop"
      "hwloc"
      "icu4c"
      "imath"
      "iperf3"
      "jasper"
      "jbig2dec"
      "jpeg"
      "jpeg-turbo"
      "jpeg-xl"
      "lame"
      "latexindent"
      "ldns"
      "leptonica"
      "libarchive"
      "libass"
      "libavif"
      "libb2"
      "libbluray"
      "libcbor"
      "libevent"
      "libffi"
      "libfido2"
      "libidn"
      "libidn2"
      "libnghttp2"
      "libogg"
      "libomp"
      "libpng"
      "libpthread-stubs"
      "librist"
      "libsamplerate"
      "libsndfile"
      "libsodium"
      "libsoxr"
      "libssh2"
      "libtasn1"
      "libtiff"
      "libtool"
      "libunibreak"
      "libunistring"
      "libuv"
      "libvidstab"
      "libvmaf"
      "libvorbis"
      "libvpx"
      "libx11"
      "libxau"
      "libxcb"
      "libxdmcp"
      "libxext"
      "libxrender"
      "libyaml"
      "libzip"
      "little-cms2"
      "lua"
      "lz4"
      "lzo"
      "m4"
      "maclaunch"
      "macvim"
      "mbedtls"
      "mold"
      "mpdecimal"
      "mpg123"
      "ncdu"
      "ncurses"
      "neofetch"
      "netpbm"
      "nettle"
      "ninja"
      "node"
      "opencore-amr"
      "openexr"
      "openjdk@11"
      "openjpeg"
      "openssh"
      "openssl@1.1"
      "openssl@3"
      "opus"
      "p11-kit"
      "pandoc"
      "pango"
      "parallel"
      "pcre"
      "pcre2"
      "perl"
      "pixman"
      "pkg-config"
      "pstree"
      "python@3.10"
      "python@3.11"
      "python@3.9"
      "pyyaml"
      "rav1e"
      "readline"
      "rubberband"
      "ruby"
      "rust"
      "screenresolution"
      "sdl2"
      "six"
      "smartmontools"
      "snappy"
      "speex"
      "sqlite"
      "srt"
      "stow"
      "svt-av1"
      "ta-lib"
      "tbb"
      "telnet"
      "tesseract"
      "theora"
      "tldr"
      "tmux"
      "unbound"
      "utf8proc"
      "w3m"
      "webp"
      "wget"
      "x264"
      "x265"
      "xmake"
      "xorgproto"
      "xvid"
      "xz"
      "zellij"
      "zeromq"
      "zimg"
      "zlib"
      "zstd"
    ];

    # `brew install --cask`
    # TODO Feel free to add your favorite apps here.
    casks = [
      "adrive"
      "aldente"
      "baidunetdisk"
      "balenaetcher"
      "bartender"
      "betterdisplay"
      "betterdummy"
      "bettertouchtool"
      "bose-updater"
      "cakebrew"
      "cloudflare-warp"
      "deepl"
      "fig"
      "fliqlo"
      "font-azeret-mono"
      "font-cascadia-code"
      "font-cascadia-code-pl"
      "font-cascadia-mono"
      "font-cascadia-mono-pl"
      "font-code-new-roman-nerd-font"
      "font-fira-code"
      "font-hack"
      "font-hack-nerd-font"
      "font-hubot-sans"
      "font-intel-one-mono"
      "font-juliamono"
      "font-mona-sans"
      "font-roboto"
      "font-roboto-flex"
      "font-roboto-mono"
      "font-roboto-mono-for-powerline"
      "font-roboto-mono-nerd-font"
      "font-roboto-serif"
      "font-roboto-slab"
      "font-sf-mono"
      "font-sf-mono-for-powerline"
      "free-download-manager"
      "hyper"
      "ieasemusic"
      "iina"
      "imazing"
      "input-source-pro"
      "ipynb-quicklook"
      "julia"
      "linearmouse"
      "mactex-no-gui"
      "maczip"
      "miniforge"
      "mochi-diffusion"
      "monitorcontrol"
      "mos"
      "motrix"
      "neteasemusic"
      "notion"
      "onedrive"
      "onyx"
      "orbstack"
      "qlcolorcode"
      "qlimagesize"
      "qlmarkdown"
      "qlstephen"
      "qlvideo"
      "qmk-toolbox"
      "qq"
      "qqmusic"
      "quicklook-json"
      "quicklookase"
      "skim"
      "snipaste"
      "sourcetree"
      "spotify"
      "telegram-desktop"
      "tencent-lemon"
      "tencent-meeting"
      "termius"
      "uninstallpkg"
      "visual-studio-code"
      "vnc-viewer"
      "wechat"
      "wechattweak-cli"
      "wechatwork"
      "xmind"
      "youku"
      "zoom"
      "zotero"
    ];
  };
}
