action_id: trunk-fmt-pre-commit
date: 2023-08-02 02:07:21
run: trunk fmt -t "git-commit" --index-file '${env.GIT_INDEX_FILE}' --upstream=HEAD
run_from: ""
trigger: pre-commit
result:
  exit_code: 2
  out: ""
  err: ""
timestamp: 1690942041
full_timestamp:
  nanos: 799023000
  seconds: 1690942041
trunk_version: 1.13.0
